# --- INIZIALIZZAZIONE ---
/vis/open OGL 800x800-0+0
/vis/verbose confirmations
/vis/viewer/set/background black
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh true
/vis/viewer/set/lineSegmentsPerCircle 100

# Disegna la geometria
/vis/drawVolume

# --- VISUALIZZAZIONE ---
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/zoom 1.4
/vis/viewer/set/auxiliaryEdge true

# --- TRAIETTORIE ---
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate

# (Consigliato con OpenGL) hard filtering
/vis/filtering/trajectories/mode hard

# --- FILTRI: escludi opticalphoton e gamma ---
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
/vis/filtering/trajectories/particleFilter-0/invert true

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-1/add gamma
/vis/filtering/trajectories/particleFilter-1/invert true

# --- MODELLI: colora i muoni ---
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set mu- blue
/vis/modeling/trajectories/drawByParticleID-0/set mu+ red